version: "3.7"

services:
  promoCarro:
    container_name: cn_promoCarro
    image: kooldev/php:7.4-nginx-sqlsrv-prod
    restart: always
    volumes:
      - "./:/app/promoCarro"
      - "./default.tmpl:/kool/default.tmpl"
    ports:
      - "8180:80"
    environment:
      - APP_NAME=promoCarro
      - PHP_FPM_LISTEN=/run/php-fpm.sock
      - NGINX_LISTEN=80
      - NGINX_ROOT=/app/promoCarro/public
      - NGINX_INDEX=index.php
      - NGINX_CLIENT_MAX_BODY_SIZE=150M
      - PHP_UPLOAD_MAX_FILESIZE=150M
      - PHP_POST_MAX_SIZE=150M
      - PHP_MEMORY_LIMIT=512M
      - NGINX_PHP_FPM=unix:/run/php-fpm.sock
      - NGINX_FASTCGI_READ_TIMEOUT=60s
      - NGINX_FASTCGI_BUFFERS=8 8k
      - NGINX_FASTCGI_BUFFER_SIZE=16k
